### ISSUE TITLE
Term page

### ISSUE THREAD

**Issue by morchickit** [TCLP-UoC/Glossary#23]
For each term show all definitions, drafting notes, applications,  related clauses and references. Include Published, last update date and a prominent link to amendment history.

**Comment by akariv** [comment]
Most of this is implemented.
We need to fix:
- Links to old glossary page that were added manually in the content itself
- There's no information regarding the clauses nor any url field which allows us to link to another location.

**Comment by akariv** [comment]
https://tclp-uoc.github.io/Glossary/term/100%25_Renewable_Energy_&_Renewable_Energy_Sources

**Comment by akariv** [comment]
Need to add here:
- [ ] Dates of creation / last update
- [ ] Links to clauses - we need the URL of each clause in AirTable

**Comment by Simone-TCLP** [comment]
this is done.
