### ISSUE TITLE
Allow publication directly from AirTable

### ISSUE THREAD

**Issue by morchickit** [TCLP-UoC/Glossary#24]
As an editor, I want to be able to decide when to publish and take off terms directly from AirTable, so I would not need to deal with multiple systems. 

We should allow for a tick button in AirTable to allow publishing and taking off terms.

**Comment by akariv** [comment]
Currently all data is coming from the 'publish' view in airtable.
Users can edit this view to select a subset of the records (e.g. filter by status or whatever other method)
