### ISSUE TITLE
Signpost to help email in both glossary homepage and term page

### ISSUE THREAD

**Issue by morchickit** [TCLP-UoC/Glossary#25]
So the user contact for help. 
Help email should appear at the bottom of the page. 
@Simone-TCLP - what email should we use?

**Comment by morchickit** [comment]
contact[at]chancerylaneproject.org

**Comment by morchickit** [comment]
@akariv - this is an easy fix.

**Comment by akariv** [comment]
Where should this Signpost be located?
Should there be some text around it, or just the email address?

**Comment by morchickit** [comment]
I wrote above, at the bottom at the page after references -
"Need help? Email us at..."
