### ISSUE TITLE
Add disclaimer to a term page

### ISSUE THREAD

**Issue by morchickit** [TCLP-UoC/Glossary#27]
Should be at the top of the page. 
Currently the disclaimer is can be expandable and is not shown until the user click on it. We should maintain it. 

Text is here: 
The definitions on this website (and published in our Climate Contract Playbook) have been prepared in good faith on a pro bono basis and are free to download and use. The definitions have been drafted and edited by a variety of lawyers and, as such, the approaches to drafting may not conform to any particular drafting norms. We acknowledge this as a consequence of the collaborative drafting process.

The definitions on this website (and published in our Climate Contract Playbook) are provided on an ‘as is’ basis and without any representation or warranty as to accuracy or that the definitions will achieve the relevant climate goal or any other outcome.

This website (and the Climate Contract Playbook) does not comprise, constitute or provide personal, specific or individual recommendations or advice of any kind, and does not contain legal or financial advice. The definitions are precedents for legal professionals to use, amend and negotiate using their professional skill and judgement and at their own risk.

While care has been taken in the drafting of these definitions, neither The Chancery Lane Project nor any of its contributors owe a duty of care to any party in relation to their preparation and do not accept any liability for any errors or omissions, nor for any loss incurred by any person relying on or using these definitions or any other person. Users should use their own professional judgement in the application of these definitions to any particular circumstance or jurisdiction or seek independent legal advice.

At present, all the definitions are based on the laws of England and Wales. We encourage the conversion of these precedent definitions for use in other jurisdictions.

**Comment by akariv** [comment]
Implemented disclaimer as in original site, copied text from there if that's ok.

**Comment by akariv** [comment]
Needs new wording for disclaimer and implement in page

**Comment by morchickit** [comment]
@Simone-TCLP a reminder about this
