### ISSUE TITLE
Embed in TCLP website

### ISSUE THREAD

**Issue by akariv** [TCLP-UoC/Glossary#34]

**Comment by morchickit** [comment]
This should be done after @Simone-TCLP is approving the prototype.

**Comment by akariv** [comment]
Not sure how exactly this embedding is supposed to be done?
Haven't we decided on the subdomain option (e.g. glossary.chancerylaneproject.org)?

**Comment by morchickit** [comment]
No, waiting on TCLP to get more details from their team
