### ISSUE TITLE
Insert TCLP logo

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#35]
Include TCLP logo top left on glossary entries page and on each glossary term page

**Comment by morchickit** [comment]
Can you add the logo here?

**Comment by Simone-TCLP** [comment]
Hi Adam

Attached as a png and as a jpg

1. PNG 

![ChanceryLaneLogo](https://user-images.githubusercontent.com/104088714/182118729-f83e1a9c-9a27-4cce-a532-a6c43bfbe69e.png)

2. JPG
![ChanceryLaneLogo](https://user-images.githubusercontent.com/104088714/182118813-d0344e8d-8430-463d-af96-b01caacc2ce0.jpg)
