### ISSUE TITLE
Font weight, size and colour matching

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#37]
All glossary pages: Is is possible to get a closer match to the font weight, size and colour of the Wordpress site? Title: "Glossary entries' is thicker and bigger. Sub-title: Standard climate-related definitions [...] is in a lighter grey in Wordpress.. Glossary entries: thicker font, darker blue

**Comment by akariv** [comment]
Both sites are identical in terms of design - please attach screenshots if it looks different on your computer.

This is how it looks like on my browser:
<img width="1017" alt="Screen Shot 2022-07-11 at 14 18 38" src="https://user-images.githubusercontent.com/265333/178253184-fdabd678-a268-438b-810c-e89a94f3b89b.png">
<img width="1025" alt="Screen Shot 2022-07-11 at 14 18 33" src="https://user-images.githubusercontent.com/265333/178253196-5fb19285-5f5e-48a8-b802-832be8a6ec70.png">

**Comment by Simone-TCLP** [comment]
Hi Adam, i double checked the zoom in settings on each browser and matched them up. They are pretty close now and I am happy with them. For reference, here are screenshots from:

(1) github page: 
<img width="397" alt="Screenshot 2022-08-01 at 11 44 21" src="https://user-images.githubusercontent.com/104088714/182121536-d2aa83a1-e1da-4417-a464-7a841f13b55b.png">

(2) the chancerylaneproject.org/glossary page: 

<img width="362" alt="Screenshot 2022-08-01 at 11 44 42" src="https://user-images.githubusercontent.com/104088714/182121619-4058e87d-36ee-4859-9bd0-033b77026da2.png">
