### ISSUE TITLE
Amend text in glossary term search bar

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#38]
Read second comment before taking action on this one: 

Glossary entries home page: change text in the search box to 

Search for a glossary term

**Comment by morchickit** [comment]
Free text will need a server computer power than what we have no which means more expensive. What is the case for free text?

**Comment by Simone-TCLP** [comment]
Understood. Let's prioritise this for next phase? 

The case for the free text search was to align the free text search approach on the Glossary page with the free text search on the climate clauses page. 

I'm happy for iteration 1 of the glossary page that we have search for term only.

**Comment by morchickit** [comment]
We can def look at it in the next version, but again, it's more $$.

**Comment by Simone-TCLP** [comment]
Current search function works fine. Closed.
