### ISSUE TITLE
Glossary term page: Is it possible to left align the bullets rather than indent them? 

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#44]
Compare: left aligned bullets in TCLP drafting notes here: 

https://chancerylaneproject.org/glossary/100-renewable-energy-renewable-energy-sources/

with GitHub drafting notes here: 

https://tclp-uoc.github.io/Glossary/term/100%25_Renewable_Energy_&_Renewable_Energy_Sources

**Comment by morchickit** [comment]
They are left aligned in both. Do you mean the indent?

**Comment by Simone-TCLP** [comment]
Yes, I meant indent. 

The bullets on chancerylaneproject.org/glossary are not indented but align with the text above and below. 

The bullets on the Github page are indented. 

I can live with this issue if it will cost a disproportionate amount of your time and costs to fix it.

**Comment by morchickit** [comment]
I think it should not be an issue to fix.
