### ISSUE TITLE
Used in title and links to clauses

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#45]
Glossary term page: After the Application section but before References insert a new heading 'Used in' and list the clauses the term is used in in alphabetical order (by Child's name).

**Comment by Simone-TCLP** [comment]
Once we have this field we can start populating it with links to the clause web pages.

**Comment by morchickit** [comment]
If a term is in more than 5 clauses show only first 5 in alphabetical order

**Comment by morchickit** [comment]
Go direct to the clause - listed as a URL

**Comment by Humzah-TCLP** [comment]
Used in clauses listed as: [Child's name] Full name of clause 

E.g: 
[Mor's clause] Climate Standard Transaction Terms

**Comment by morchickit** [comment]
@akariv - Clauses table is here - https://airtable.com/app78p8j3otk9SME6/tblybiJmttMkUEUGk/viwh7PSKZUq07ULhu?blocks=hide

If no clause is mentioned no need to add that section.

**Comment by akariv** [comment]
1. Where can I find the full name of the clause?
2. Should it link somewhere, or just be a list of text lines?

**Comment by morchickit** [comment]
We need to discuss #61 tomorrow before we proceed with this.
