### ISSUE TITLE
Remove underlining from references sections

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#46]
Glossary term page: Remove underlining from blue references links. See '1.5 Aligned' as an example

**Comment by morchickit** [comment]
I can't see any underlining on my computer. Can you upload a screenshot please?

**Comment by Simone-TCLP** [comment]
This bug occurred as a one off in the 1.5 Aligned term. It has since corrected. Thank you, I'll close this comment now.
