### ISSUE TITLE
Make font consistent size. Font of the bulleted text in the Drafting notes section is smaller

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#47]
See Abatement Measures as an example

**Comment by morchickit** [comment]
@akariv - heads up

**Comment by Simone-TCLP** [comment]
I can live with this anomaly if it will cost a disproportionate amount of time and effort to fix it.  Let me know if it is a fairly quick fix or not. Thank you.

**Comment by akariv** [comment]
This should be fixed now - if there's still a mismatch, please attach a screenshot.
