### ISSUE TITLE
Query on hyperlinks

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#50]
Many definitions and drafting notes refers to glossary terms and are hyperlinked. Should these hyperlinks be to (a) the github website page or (b) the TCLP address. I'm thinking (a) but please confirm. TCLP will review the glossary and update these links subject to your response.

**Comment by morchickit** [comment]
I believe it's actually b once it's on the TCLP domain

**Comment by akariv** [comment]
It's best if these links are left relative (e.g.
'term/Neutralisation_Measures/'), so that they would work regardless of the
website's address.

**Comment by Simone-TCLP** [comment]
I put my question badly. To re-phrase: 

Glossary terms in the **GitHub glossary site** cross refer to other glossary terms. An example is [Neutralisation Measures](https://tclp-uoc.github.io/Glossary/term/Neutralisation_Measures) where the drafting notes refer to [Carbon Capture and Storage](https://chancerylaneproject.org/glossary/carbon-capture-carbon-capture-storage-ccs-carbon-capture-usage-and-storage-ccus/) (on the TCLP Wordpress page). 

My question is - once we take down the Wordpress site and replace it with the GitHub one, all cross references on Github site that point to the Wordpress site will be broken. 

The answer is - where there is a cross reference, it needs to point to the term address in the Github site, not the Wordpress site. 

This is an admin job for TCLP to do. 

@Humzah-TCLP 

The answer to my question is this: 

Where a cross reference to a glossary term points to the TCLP wordpress page we need to replace that hyperlink with the Github web address.

**Comment by akariv** [comment]
Simone, just so the link don't break again when (for example) the domain
for the glossary page is changed (we plan to do it sometime soon, but it
might happen again), I suggested using relative likes and not absolute ones.
For example 'term/Neutralisation_Measures' instead of '
https://tclp-uoc.github.io/Glossary/term/Neutralisation_Measures'.
This way the links will keep working even if the website's location changes.

**Comment by Simone-TCLP** [comment]
Hi Adam, so to check that I have understood correctly: 

Here's a screenshot of Option 2 definition from the term 'Carbon Footprint': 

<img width="362" alt="Screenshot 2022-08-01 at 11 13 43" src="https://user-images.githubusercontent.com/104088714/182115570-3d96645c-1bdc-4476-95b7-fac0972ce04e.png">

It cross refers to another glossary term Carbon Dioxide Equivalent. The url for Carbon Dioxide Equivalent is "https://chancerylaneproject.org/glossary/hgv/" 

You propose that I replace this with term/Carbon_Dioxide_Equivalent? 

FYI for this particular glossary term it has alternative CO2e and CO2 which are expressed in the github url address as "%28CO2e_or_CO2eq%29 " 

Does this mean that I should use term/Carbon_Dioxide_Equivalent_%28CO2e_or_CO2eq%29 

Is that right?

**Comment by Simone-TCLP** [comment]
Hi @akariv 

I'm keen to start updating the hyperlinks in the Glossary and just want to check I have understood how to do this correctly (see my message above) and how I have dealt with cross references to terms Abatement Measures and Mitigation Hierarchy in the drafting notes of glossary term Neutralisation Measures (screenshot below). Have I done it right?

<img width="392" alt="Screenshot 2022-08-02 at 09 21 53" src="https://user-images.githubusercontent.com/104088714/182316382-4670bc06-6097-400d-83f8-ce9eba806fce.png">

**Comment by akariv** [comment]
Hey @Simone-TCLP 

The links should be of the form `term/Carbon_Dioxide_Equivalent_(CO2e_or_CO2eq)`

There's no need to do any sort of character encoding (using percent signs).

When adding links in AirTable, simple select the text which will be displayed to the user, click on 'link', 

<img width="175" alt="Screen Shot 2022-08-07 at 21 00 32" src="https://user-images.githubusercontent.com/265333/183304734-3c2d225e-0ad9-4ba8-8abb-f13cc2c13077.png">

type in the link contents and click on 'Done':

<img width="288" alt="Screen Shot 2022-08-07 at 21 00 41" src="https://user-images.githubusercontent.com/265333/183304738-91d7ccd0-8798-458e-b66b-fd857de2a975.png">

**Comment by Simone-TCLP** [comment]
Hi Adam, thank you. 

So, in your sustainability example above what should be typed in black box is 

term/Link_To_The_Page 

OR 

term/Sustainability?

Maybe we can have a 2 min chat just so i'm clear?

S

**Comment by akariv** [comment]
in the black box you should type the actual link to the page - the one
starting with `term/...`

So in my example, you would indeed use `term/Sustainability`.

**Comment by Simone-TCLP** [comment]
Got it, thank you. I'll arrange for someone at TCLP to update all the links during the course of this week.
