### ISSUE TITLE
How can we add a formula to Airtable (definition of Neutralisation Measures)

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#52]
<img width="446" alt="Screenshot 2022-06-21 at 11 43 49" src="https://user-images.githubusercontent.com/104088714/174781833-28edbf04-e1d6-4d1b-b5b9-896a4b9a549c.png">

We need to put the E looking formula into the definition for Neutralisation measures. To replace the text "n=0kSn-Enn=1kGn"

**Comment by morchickit** [comment]
@akariv - thoguhts?

**Comment by akariv** [comment]
It's possible to add an image to the markdown text by embedding html code
inside (i.e. '<img src="..."/>')
Then, we could add a link to the image of the equation (if it's hosted
somewhere), or encode it using a data-url (e.g. using this tool
https://dopiaza.org/tools/datauri/index.php or similar)

**Comment by akariv** [comment]
I took the liberty of running that process for this specific item - you can see the result here:

https://tclp-uoc.github.io/Glossary/term/Neutralisation_Measures
