### ISSUE TITLE
Shared Socio-Economic Pathway - remove extra paragraph space

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#54]
In Drafting notes, there is a spare space between the end of SSP3 and the heading SSP4. I've tried to format and get rid of it but without success!
<img width="282" alt="Screenshot 2022-08-01 at 13 27 34" src="https://user-images.githubusercontent.com/104088714/182138450-26a68928-0116-4b01-8aea-fd4f73552222.png">
?

**Comment by akariv** [comment]
Done
