### ISSUE TITLE
Net Zero Transition Plan - missing Related terms box

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#58]
TCLP glossary page for this term has related terms box (see screenshot). 
<img width="366" alt="Screenshot 2022-08-05 at 17 04 03" src="https://user-images.githubusercontent.com/104088714/183117293-2feddd9f-5f01-4eff-aaf8-bb2e846d3aae.png">
.

Github page does not even though the terms are in Airtable

**Comment by akariv** [comment]
Duplicate of #48
