### ISSUE TITLE
Drafting notes in quick links box

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#60]
Please correct 'Drafting Notes to small n 'Drafting notes' in the quick links box. 

Here is what it looks like currently. 
<img width="153" alt="Screenshot 2022-08-08 at 09 39 04" src="https://user-images.githubusercontent.com/104088714/183376876-aaa11098-b82f-4698-8d0b-2e3e2d243aa5.png">

Our house style is no unnecessary capitalisation so: 
-  'Drafting notes'
-  'Used in'

**Comment by morchickit** [comment]
@Humzah-TCLP @Simone-TCLP - can you review that this is done and ok?

**Comment by Humzah-TCLP** [comment]
Reviewed. All ok!
