### ISSUE TITLE
/term command issue

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#65]
Hello @morchickit and @akariv 

the command 

/term/[glossary_term] and 
term/[glossary_term] 

does not result a hyperlink to the glossary term in question. It is published on the web page as narrative text on the web page.  An example is here in the 'Drafting notes' of Alternative Fuel. 

<img width="451" alt="Screenshot 2022-09-20 at 09 14 46" src="https://user-images.githubusercontent.com/104088714/191204757-c20b4056-f0e0-4add-8744-61251735ac2f.png">

**Comment by akariv** [comment]
Hey @Simone-TCLP -

This is not a command, but the actual URL to use - see the following clip as an example on how to create it in AirTable:

![Example](https://user-images.githubusercontent.com/265333/191213518-1f544632-0abe-446b-8b87-6df358a2a073.gif)

**Comment by Simone-TCLP** [comment]
Thanks @akariv - the hyperlink command still doesn't work. It only works if you hyperlink to the full URL being 

https://glossary.chancerylaneproject.org/term/Greenhouse_Gases_%28GHGs%29

**Comment by akariv** [comment]
What do you mean by doesn't work? What happens when you click the link in the website? Can you share an example of a non working one?

**Comment by Simone-TCLP** [comment]
When you hyperlink the text Greenhouse Gas to http:///term/Greenhouse_Gases_%28GHGs%29 - you get "This site can't be reached". I have instead been hyperlinking the text to the full url but that raises an issue if at some point in the future we change the url, right e.g. replace glossary.chancerylaneproject.org with something else. 

<img width="1006" alt="Screenshot 2022-09-22 at 08 09 54" src="https://user-images.githubusercontent.com/104088714/191681388-9339de53-44e5-420a-a14f-bb578527d79d.png">

**Comment by akariv** [comment]
Yes -

The reason for that is that the link should be
"http:///term/Greenhouse_Gases_(GHGs)"
and not "http:///term/Greenhouse_Gases_%28GHGs%29" - i.e. without the
cryptic percent signs, but the id exactly as it appears in AirTable.

**Comment by Simone-TCLP** [comment]
Ok. I've changed it to: 

https///term/Greenhouse_Gas_%2528GHG%2529_Emissions

I copied and pasted the greenhouse gas element directly out of the url. 

This hyperlink takes me to this page with no content on it
<img width="744" alt="Screenshot 2022-09-22 at 09 16 56" src="https://user-images.githubusercontent.com/104088714/191695080-a582449f-fd8d-40dd-b42e-11598e62a158.png">

**Comment by akariv** [comment]
No, the link should be   "http:///term/Greenhouse_Gases_(GHGs)"
and __not__                      "http:///term/Greenhouse_Gases_%28GHGs%29"

__without__ the cryptic percent signs, but the id __exactly as it appears in AirTable__:

<img width="496" alt="Screen Shot 2022-09-22 at 12 29 54" src="https://user-images.githubusercontent.com/265333/191711821-4f664ae7-76e4-42c4-926e-e0772eff7927.png">

also note that it should start with '/term/', you don't need to add http:// or https:// to it.

**Comment by Simone-TCLP** [comment]
Can we have a call. We're going back and forward on this one and we can probably put these issues to rest more easily with a chat. I'm around this afternoon and tomorrow for a short call at a time that suits you.

**Comment by akariv** [comment]
Sure, I'm free now

**Comment by Simone-TCLP** [comment]
Thank you Adam - here is google meet -
https://meet.google.com/yzq-noir-vjf?authuser=0

**Comment by Simone-TCLP** [comment]
Hi @akariv 

I have punched

/term/Greenhouse_Gas_(GHG)_Emissions into Option 1 of 1.5C Aligned. It points to a broken link. 

The /term formulation is working for other terms Climate Change, Climate Change Mitigation Measures so not sure what is happening with GHG Emissions?

**Comment by Simone-TCLP** [comment]
Hi @akariv 

I'm really sorry but the hyperlinking is highly problematic and is not working.

(1) Sometimes the link opens the linked term in the same window as the glossary term I was reading. This means I have to click 'Back' to return to the main term I was reading. 
Example: Adverse Climate Outcome - Option 1. Click on Air Quality.  It opens a window over Adverse Climate Outcome. I have to click 'BACK' to return to Adverse Climate Outcome. 

(2) Other times the link opens a separate window to the one I am reading the main term in. This is good. However, for the links Greenhouse Gas Emissions, Natural Capital and Embedded Carbon in Adverse Climate Outcome Option 1, they direct you to a blank page. Screenshot attached. 

<img width="793" alt="Screenshot 2022-09-23 at 19 06 36" src="https://user-images.githubusercontent.com/104088714/192030184-45429496-5b65-43bd-8124-839193699558.png">

(3) Having put in all the hyperlinks into Adverse Climate Outcome option 1 all of the formatting has been stripped out of it. I have tried to type it back in but it is not publishing on the website. Screenshots attached. 
Screenshot 1: List present in Airtable
<img width="802" alt="Screenshot 2022-09-23 at 19 09 02" src="https://user-images.githubusercontent.com/104088714/192030407-bf5de8e3-b8f2-482f-a6af-fffe75450cb9.png"> 

Screenshot 2: Not publishing to web page.
<img width="667" alt="Screenshot 2022-09-23 at 19 08 25" src="https://user-images.githubusercontent.com/104088714/192030360-83792788-fd1a-4faf-9f77-20c58e2d213e.png">

**Comment by akariv** [comment]
Hey @Simone-TCLP  - 
I found the bug that causes these issues, they should all be solved now in the website (didn't change AirTable).
Can you please confirm?

**Comment by Simone-TCLP** [comment]
Hi @akariv thank you so much. I am travelling for the next couple of days but will try check it out on Thursday. thanks for the fix . S
