### ISSUE TITLE
Can we select entries to hold back from publication

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#67]
Or do they need to be deleted out of airtable? 

e.g. if we want to publish but hold back Base Year and Like For Like from publication because they need more work. Can we create some code that tells Airtable to publish some terms and not others?

**Comment by morchickit** [comment]
This is still open, I will speak to @akariv about this

**Comment by Simone-TCLP** [comment]
Hi @akariv @morchickit 

The terms that must be hidden from publication view by close today are

Invasive Non Native Species
Just transition 
Like for Like 
Neutralisation Measures 
Net Zero GHG Emissions Statement & Carbon Neutral Statement 
NZ target boundaries 
Offshoring 
Science Based Target 
Shared Socio-Economic Pathway

**Comment by morchickit** [comment]
All done! 
There is now a column named show on site. If it ticked, it is on the site. Notice this is filtered, so if you want to bring the term back you will have to unfiltered, tick it and then filter again.

**Comment by Simone-TCLP** [comment]
Thank you very much Mor.
